server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

dataSourceFactory:
  # the name of your JDBC driver
  driverClass: com.mysql.cj.jdbc.Driver

  # the username
  user: root

  # the password
  password: Nitheez@iiit1

  # the JDBC URL
  url: jdbc:mysql://localhost:3306/flipfit_gym?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.hbm2ddl.auto: update
    hibernate.show_sql: true
    hibernate.format_sql: true

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* FlipFit Health Check */ SELECT 1"

  # the timeout before a connection validation queries fail
  validationQueryTimeout: 3s

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 10s

  # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
  minIdleTime: 1 minute

logging:
  level: INFO
  loggers:
    com.flipfit: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Metrics configuration
metrics:
  frequency: 1 minute
  reporters:
    - type: console
      timeZone: UTC
